/*
* author: Sam Ford
* desc: Static class purely for storing File Section constants
* date started: approx 6/18/2023
*/

namespace DecisionMaker
{
    internal static class FileSectConstants
    {
        internal enum FileTypeCodes
        {
            DCFiles = 1,
            ProfileFiles,
            WipFile
        }

        internal enum FileActionCodes 
        {
            DeleteAll = -1,
            ViewFile = 1,
            DeleteFile
        }

        internal enum ProfileActionCodes
        {
            GREETING = 1,
            DEPARTING,
            DISPLAYNAME
        }
        internal const string DEFAULT_FILES_DIR = ".\\FileManagement\\";
        internal const string DEFAULT_WIP_FILE = DEFAULT_FILES_DIR + "wipcat";
        internal const string FM_GREETING = "Welcome to File Management. This is where you can delete any files generated by this program.";
        internal const string FS_ERR_HEADER = "FilesSection.cs: ";
        internal static readonly string[] fileTypes = { "Decision Categories", "Custom Profile", "WIP File" };
        internal static readonly string[] manageFileActions = {"View contents", "Delete file"};
        internal static readonly string[] manageProfileActions = { "Greeting", "Exiting", "Display Name" };
    }
}