/*
* author: Sam Ford
* desc: Static class purely for storing Decision Section constants
* date started: approx 6/18/2023
*/

namespace DecisionMaker
{
    public static class FileSectConstants
    {
        public enum FileTypeCodes
        {
            DCFiles = 1,
            ProfileFiles,
            WipFile
        }

        public enum FileActionCodes 
        {
            DeleteAll = -1,
            ViewFile = 1,
            DeleteFile
        }

        public enum ProfileActionCodes
        {
            GREETING = 1,
            DEPARTING,
            DISPLAYNAME
        }
        public const string DEFAULT_FILES_DIR = ".\\FileManagement\\";
        public const string DEFAULT_WIP_FILE = DEFAULT_FILES_DIR + "wipcat";
        public const string FM_GREETING = "Welcome to File Management. This is where you can delete any files generated by this program.";
        public const string FS_ERR_HEADER = "FilesSection.cs: ";
        public static readonly string[] fileTypes = { "Decision Categories", "Custom Profile", "WIP File" };
        public static readonly string[] manageFileActions = {"View contents", "Delete file"};
        public static readonly string[] manageProfileActions = { "Greeting", "Exiting", "Display Name" };
    }
}